#配置视图解析器
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  #关联redis
  profiles:
    active: redis
#配置注册服务中心
dubbo:
  application:
    name: jd_passport
  registry:
    address: zookeeper://192.168.175.129:2181
  protocol:
    name: dubbo
    port: 20884

#给当前微服务配置tomcat服务器端口
server:
  port: 8084